#!/usr/bin/env bash
set -e
MAJOR=7
VERSION=${MAJOR}.0.54

dir=apache-tomcat-$VERSION
archive=$dir.tar.gz

if [ ! -e $archive ];then
    wget http://archive.apache.org/dist/tomcat/tomcat-${MAJOR}/v${VERSION}/bin/${archive}
fi
tar xvf $archive

pushd $dir
for p in $(find ../patches/perf/ -name '*.patch' | sort); do
    echo "Applying $p"
    patch -p1 < $p
done
popd

rm -rf ROOTFS
mkdir -p ROOTFS/usr
mv $dir ROOTFS/usr/tomcat
