#!/usr/bin/env bash

if [ ! -e upstream ];then
	mkdir upstream
fi 

if [ ! -e ROOTFS ];then
	mkdir -p ROOTFS/data/lucene
	mkdir -p ROOTFS/data/lucene/trunk/lucene
	mkdir -p ROOTFS/data/lucene/logs
        touch  ROOTFS/data/lucene/logs/log.txt
fi 

cd upstream

if [ ! -e lucene.src ];then
       svn checkout https://svn.apache.org/repos/asf/lucene/dev/trunk lucene.src
fi

if [ ! -e util ];then
	hg clone https://hg.codespot.com/a/apache-extras.org/luceneutil/ util 
	cd util
	patch -p1 <  ../../compile-only.patch
	cd ..
fi

if [ ! -e patch ]; then
	ln -sf lucene.src patch
fi

if [ ! -e trunk ]; then
	ln -sf lucene.src trunk
fi

tar xf ../indices.tar.gz

cd util
cp tasks/wikimedium.1M.nostopwords.tasks my.tasks
cp tasks/wikimedium.1M.nostopwords.tasks .
python src/python/setup.py
python src/python/localrun.py -source wikimedium10k -compile-only
mkdir logs  >/dev/null 2>&1
touch logs/mylog.txt
cd ..

ROOTDIR=../ROOTFS/data/lucene
cp -a indices $ROOTDIR
cp -a util $ROOTDIR
cp -a trunk/lucene/build $ROOTDIR/trunk/lucene

# Task files
#cp -a ../IntNRQ.tasks $ROOTDIR/util/my.tasks
#cp -a ../IntNRQ.tasks ../upstream/util/my.tasks
cd ..
cp host.sh ROOTFS/data/lucene
echo Setup Done

exit 0
